name: Build

on:
  push:
    paths-ignore:
        - '.gitignore'
        - 'docs/*'
        - 'themes/*'
        - 'README.md'
        - 'LICENSE'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake g++
      - name: Create Build Directory
        run: mkdir build && cd build
      - name: Configure CMake
        run: cmake ..
        working-directory: ./build
      - name: Build
        run: cmake --build .
        working-directory: ./build
      - name: Upload Linux Binary
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: build/nino

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' && choco install mingw
      - name: Create Build Directory
        run: mkdir build && cd build
      - name: Configure CMake
        run: cmake -G "MinGW Makefiles" ..
        working-directory: ./build
      - name: Build
        run: cmake --build .
        working-directory: ./build
      - name: Upload Windows Binary
        uses: actions/upload-artifact@v4
        with:
          name: windows-binary
          path: build/nino.exe
